version: '3'

services:
  web:
    image: jamesmillar/course-service:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongo
      - RUN_TESTS=false
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
volumes:
  mongo-data: